FORWARD_SPEED_LEFT = 0.2
FORWARD_SPEED_RIGHT = 0.2

SPIN_SPEED_LEFT = 0.2
SPIN_SPEED_RIGHT = 0.2

SPIN_TIME = 10  # In sec
WANDER_TIME = 15 # In sec

OPEN_CLAW_PAUSE = 2  # In sec
CLOSE_CLAW_PAUSE = 2  # In sec

PIXY_BOUNDARY_LEFT = 100
PIXY_BOUNDARY_RIGHT = 200

PING_CONE_THRESHOLD = 5  # In cm
