FORWARD_SPEED_LEFT = 0.15
FORWARD_SPEED_RIGHT = 0.15

SPIN_SPEED_LEFT = 0.15
SPIN_SPEED_RIGHT = 0.15

SPIN_SPEED_LEFT_FAST = 0.15
SPIN_SPEED_RIGHT_FAST = 0.15

SPIN_TIME = 10  # In sec
WANDER_TIME = 30 # In sec

OPEN_CLAW_PAUSE = 2  # In sec
CLOSE_CLAW_PAUSE = 2  # In sec

PING_CONE_THRESHOLD = 5  # In cm
PING_WALL_THRESHOLD = 15
IR_WALL_THRESHOLD = 200

PIXY_BOUNDARY_LEFT = 100
PIXY_BOUNDARY_RIGHT = 200
PIXY_CONE_SIGNATURE = [1]
PIXY_TARGET_SIGNATURE = [1]
