FORWARD_SPEED_LEFT = 0.15
FORWARD_SPEED_RIGHT = 0.18

SPIN_SPEED_LEFT = 0.14
SPIN_SPEED_RIGHT = 0.14

SPIN_SPEED_LEFT_FAST = 0.15
SPIN_SPEED_RIGHT_FAST = 0.15

SPIN_TIME = 10  # In sec
WANDER_TIME = 30 # In sec

OPEN_CLAW_PAUSE = 2  # In sec
CLOSE_CLAW_PAUSE = 2  # In sec

PING_CONE_THRESHOLD = 5  # In cm
IR_TARGET_THRESHOLD = 300

PING_WALL_THRESHOLD = 15
IR_WALL_THRESHOLD = 200

PIXY_BOUNDARY_LEFT = 100
PIXY_BOUNDARY_RIGHT = 200

# Do not use signature 3!
# 1 - Orange
# 2 - Green
# 4 - Blue
MAX_PIXY_BLOCKS = 20

PIXY_ORANGE_CONE = [1]
PIXY_BLUE_CONE = [2]
PIXY_NULL = [-1]

PIXY_CONE_SIGNATURE = [PIXY_ORANGE_CONE, PIXY_BLUE_CONE, PIXY_NULL]
PIXY_TARGET_SIGNATURE = [3]

# Robot IP
GROUP10_IP = "192.168.43.139:5000"
GROUP10_ENDPOINT_READY = "/activate10"
